POST http://localhost:3001/api/generate-map
Content-Type: application/json

{
    "concept": "Liason in French"
}

###

POST http://localhost:3001/api/generate-map
Content-Type: application/json

{
    "concept": "newton's laws of motion",
    "level": "undergraduate"
}

###

POST http://localhost:3001/api/generate-map
Content-Type: application/json

{
    "concept": "conjugation of re verbs",
    "level": "high school"
}

###

POST http://localhost:3001/api/generate-map
Content-Type: application/json

{
    "concept": "how to make omelette",
    "level": "high school"
}

###

POST http://localhost:3001/api/generate-map
Content-Type: application/json

{
    "concept": "how to make a cup of tea",
    "level": "high school"
}

###

POST http://localhost:3001/api/generate-map
Content-Type: application/json

###

POST https://vertex-server-470b.onrender.com/api/generate-map
Content-Type: application/json

{
    "concept": "Liason in French"
}

###

POST https://vertex-server-470b.onrender.com/api/generate-map
Content-Type: application/json

